identifier_fb: '798111266883512'
secret_fb: '6c0ba0bd324eecc9a7431506638fe4db'
identifier_tw: 'Gr4leTgf50nAXgpFGyzmEbo7o'
secret_tw: 'fIYp5Cm0OMPCLfaMdJoyU6ptQoEaUoYAPoqgOiGw70l4OuQzMC'
identifier_gg: '950230205484.apps.googleusercontent.com'
secret_gg: 'uqhwRbEpiyBWqunPjwhHlZkH'

